# Generated by Django 3.1.4 on 2021-01-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_web', '0003_auto_20210105_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
